
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: testUser
    password: thisisTESTpw!#%&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always